[package]
name = "gibson"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.12", features = ["dynamic_linking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
noise = "0.8"
rand = "0.8"
itertools = "0.12"
nalgebra = "0.32"